package SQLprovider;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import connection.DBConnection;
import models.Medicine;
import usageModels.MedicineUsage;

public class MedicineProvider extends DBConnection{
    protected  void useMedicine(int medicineID, int patientID) {

        //Query Remaining

        //query remaining
        
        PreparedStatement preparedStatement = null;
        try {
            String sql = "";
            preparedStatement = getConnection().prepareStatement(sql);
            int rows = preparedStatement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (preparedStatement != null) {
                    preparedStatement.close();
                }
                closeConnection();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }


//     CREATE TABLE MEDICINE_DETAILS (
//     MEDICINE_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     MEDICINE_NAME VARCHAR(255),
//     MEDICINE_CHARGE_PER_UNIT DECIMAL(10, 2),
//     UNITS INT,
//     BATCH_NO VARCHAR(50)
// );

    protected  ArrayList<Medicine> showAllMedicines() {
        ArrayList<Medicine> allMedicineList = new ArrayList<Medicine>();
        PreparedStatement preparedStatement = null;
        ResultSet result = null;
        try {
            String sql = "Select * from MEDICINE_DETAILS";
            preparedStatement = getConnection().prepareStatement(sql);
            result = preparedStatement.executeQuery();
            Medicine medicine = new Medicine();
            while(result.next())
            {
                medicine.setMedicineId(result.getInt("MEDICINE_ID"));
                medicine.setMedicineName(result.getString("MEDICINE_NAME"));
                medicine.setMedicineChargePerUnit(result.getFloat("MEDICINE_CHARGE_PER_UNIT"));
                medicine.setUnits(result.getInt("UNITS"));
                medicine.setBatchNo(result.getString("BATCH_NO"));
                allMedicineList.add(medicine);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (preparedStatement != null) {
                    preparedStatement.close();
                }

                if (result != null) {
                    result.close();
                }
                closeConnection();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
        return allMedicineList;
    }


//     CREATE TABLE MEDICINE_USAGE (
//     MEDICINE_USAGE_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     MEDICINE_ID INT NOT NULL,
//     PATIENT_ID INT NOT NULL,
//     USAGE_COUNT INT NOT NULL,
//     U_DATE DATE,
//     CONSTRAINT FK_MEDICINE_ID FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE_DETAILS(MEDICINE_ID),
//     CONSTRAINT FK_ME_PATIENT_ID FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
// );


    protected  ArrayList<MedicineUsage> showMedicinesByPatientID(int patientID) {
        ArrayList<MedicineUsage> medTestList = new ArrayList<MedicineUsage>();
        PreparedStatement preparedStatement = null;
        ResultSet result = null;
        try {
            String sql = "Select * from MEDICINE_USAGE where PATIENT_ID=?";
            preparedStatement = getConnection().prepareStatement(sql);
            preparedStatement.setInt(1, patientID);
            result = preparedStatement.executeQuery();
            MedicineUsage usedMedicine = new MedicineUsage();
            while(result.next())
            {
                usedMedicine.setMedicineSegmentId(result.getInt(""));
                usedMedicine.setMedicineId(result.getInt(""));
                usedMedicine.setPatientId(result.getInt(""));
                usedMedicine.setUsageCount(result.getInt(""));
                usedMedicine.setDate(result.getDate(""));
                medTestList.add(usedMedicine);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (preparedStatement != null) {
                    preparedStatement.close();
                }

                if (result != null) {
                    result.close();
                }
                closeConnection();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
        return medTestList;
         //SQL Query goes here
    }
}
