

-- insert treatment and services 

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Consultation', 200.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Prescription Medication', 50.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Physical Therapy', 300.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Occupational Therapy', 250.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Speech Therapy', 200.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Chemotherapy', 1000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Radiation Therapy', 800.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Surgery', 5000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Acupuncture', 150.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Chiropractic Adjustment', 75.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Massage Therapy', 100.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Psychiatric Evaluation', 300.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Behavioral Therapy', 200.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Nutrition Counseling', 150.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Hypnotherapy', 250.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Yoga Therapy', 100.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Cosmetic Surgery', 10000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Dental Implants', 5000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('LASIK Eye Surgery', 3000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Hair Transplantation', 8000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Laser Hair Removal', 500.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Tattoo Removal', 250.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Body Contouring', 2000.00);

INSERT INTO TREATMENT_SERVICES_DETAILS (TREATMENT_NAME, TREATMENT_CHARGE)
VALUES ('Liposuction', 4000.0);



-- insert room details
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('ICU', 500.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('ICU', 500.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Private', 200.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('Semi-private', 125.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('General', 75.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('ICU', 500.00);
INSERT INTO ROOM_DETAILS (ROOM_TYPE, ROOM_CHARGE) VALUES ('ICU', 500.00);



INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Emily Wang', 'MD', 'Psychiatry', 225.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. James Park', 'MBBS', 'Orthopedics', 275.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Karen Wong', 'MD', 'Neurology', 350.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Mark Johnson', 'MBBS', 'Gastroenterology', 225.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Elizabeth Nguyen', 'MD', 'Endocrinology', 275.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Emily Lang', 'MD', 'Psychiatry', 225.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. James Peter', 'MBBS', 'Orthopedics', 275.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. kyle Wong', 'MD', 'Neurology', 350.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Larry Johnson', 'MBBS', 'Gastroenterology', 225.00);

INSERT INTO DOCTOR_DETAILS (DOCTOR_NAME, QUALIFICATION, SPECIALTY, CONSULTATION_CHARGE) VALUES
('Dr. Mike Pots', 'MD', 'Endocrinology', 275.00);


-- medicines
INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Paracetamol', 1.50, 100, 'ABCD1234');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Amoxicillin', 3.25, 50, 'EFGH5678');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Aspirin', 2.00, 75, 'IJKL9012');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Lisinopril', 5.00, 25, 'MNOP3456');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Metformin', 2.50, 50, 'QRST7890');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Ibuprofen', 3.75, 50, 'UVWX1234');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Ciprofloxacin', 4.50, 30, 'YZAB5678');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Losartan', 6.25, 20, 'CDEF9012');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Simvastatin', 3.00, 40, 'GHIJ3456');

INSERT INTO MEDICINE_DETAILS (MEDICINE_NAME, MEDICINE_CHARGE_PER_UNIT, UNITS, BATCH_NO)
VALUES ('Levothyroxine', 2.75, 60, 'KLMN7890');



-- equipments 
INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Blood Gas Analyzer', 2500, 'Diagnostic', 7);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Patient Monitor', 1000, 'Monitoring', 15);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Infusion Pump', 500, 'Life Support', 20);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Anesthesia Machine', 7000, 'Surgical', 3);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Laryngoscope', 250, 'Emergency', 12);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('ECG Machine', 1500, 'Diagnostic', 10);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Ventilator', 5000, 'Life Support', 5);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Defibrillator', 2000, 'Emergency', 8);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Ultrasound Machine', 3000, 'Diagnostic', 6);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('X-ray Machine', 4000, 'Diagnostic', 4);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Autoclave', 3000, 'Sterilization', 5);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Blood Pressure Monitor', 500, 'Monitoring', 20);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Nebulizer', 200, 'Respiratory', 15);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Pulse Oximeter', 400, 'Monitoring', 10);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Suction Machine', 1000, 'Life Support', 8);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('C-Arm', 12000, 'Surgical', 2);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Dialysis Machine', 8000, 'Life Support', 4);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Fetal Monitor', 1500, 'Monitoring', 6);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('MRI Machine', 15000, 'Diagnostic', 1);

INSERT INTO EQUIPMENT_DETAILS (EQUIPMENT_NAME, EQUIPMENT_CHARGE_PER_UNIT, EQUIPMENT_CATEGORY, UNITS_AVAILABLE)
VALUES ('Surgical Table', 5000, 'Surgical', 3);



-- medical tests
INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Flu Test', 50.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Strep Throat Test', 40.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Tuberculosis (TB) Test', 80.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Hepatitis C Test', 100.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Lyme Disease Test', 120.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('H. pylori Test', 60.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Syphilis Test', 90.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('HIV Viral Load Test', 150.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Complete Metabolic Panel (CMP)', 125.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Thyroid Antibody Test', 100.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Cancer Antigen (CA) 125 Test', 200.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('C-reactive Protein (CRP) Test', 50.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Blood Typing', 40.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Hemoglobin A1C Test', 60.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('HIV Test', 100.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Hepatitis B Test', 80.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Mammogram', 150.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Prostate-Specific Antigen (PSA) Test', 90.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Bone Density Test', 200.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Eye Exam', 75.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Skin Biopsy', 120.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Complete Blood Count (CBC)', 50.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Urinalysis', 30.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Chest X-ray', 75.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Electrocardiogram (ECG)', 100.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Pap Smear', 60.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Colonoscopy', 250.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Magnetic Resonance Imaging (MRI)', 500.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Ultrasound', 150.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Complete Physical Examination', 200.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Blood Glucose Test', 25.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Thyroid Function Test', 80.00);

INSERT INTO MEDICAL_TESTS (TEST_NAME, TEST_CHARGE)
VALUES ('Spirometry', 120.00);